---
- name: Check if JDK installed
  stat: path=/opt/jdk1.8.0_65/
  register: jdk_installed

- name: Get JDK
  command: curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o /tmp/jdk-8u65-linux-x64.tar.gz  http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.tar.gz
  when: jdk_installed.stat.exists == False

- name: Explode JDK tar
  unarchive: src=/tmp/jdk-8u65-linux-x64.tar.gz dest=/opt copy=no
  when: jdk_installed.stat.exists == False

- name: Setup Java binaries
  shell: update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_65/bin/java 1
  when: jdk_installed.stat.exists == False

- name: Setup Javac binaries
  shell: update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_65/bin/javac 1
  when: jdk_installed.stat.exists == False

- name: Setup Jar binaries
  shell: update-alternatives --install /usr/bin/jar jar /opt/jdk1.8.0_65/bin/jar 1
  when: jdk_installed.stat.exists == False